### ISSUE TITLE
Introduce a YAML coding standard

### ISSUE THREAD

**Issue by szepeviktor** [web-platform-dx/web-features#1477]
### Specification

It would be nice to declare how YAML files should be written.

### Description

`yamllint` is our friend.
https://yamllint.readthedocs.io/en/stable/

[_source_](https://github.com/szepeviktor/byte-level-care/blob/01061a22e9a9211b3af984581e65c5ec4ab80943/.github/workflows/yaml.yml#L47-L54)

### Browser support

n/a

**Comment by ddbeck** [comment]
Interesting idea, @szepeviktor. I have not heard of this tool before. A couple of questions:

We have Prettier running against some of the YAML files already. Do you know if this tool would conflict with that?

Also, have you tried running this tool against the existing YAML files? What kinds of issues do we currently have that this would correct?

**Comment by szepeviktor** [comment]
> What kinds of issues do we currently have that this would correct?

The main issue is: the desired state is unknown. 
These two dozen rules help you to have uniform YAML files.
https://yamllint.readthedocs.io/en/stable/rules.html

**Comment by ddbeck** [comment]
> Basically we need two dozen decisions.

Ah, I figured it was an opinionated tool. I guess my feeling is that, in the absence of an actual conflict or inconsistency creating a problem for feature authors, then I don't want to choose a bunch of rules for the sake of choosing rules. If there's a specific style issue that's causing trouble, then let's deal with that (maybe even with this tool), but I'd prefer to avoid speculatively worrying about style.

**Comment by szepeviktor** [comment]
`.yamllint.yml`
```yaml
extends: "default"

rules:
    document-start:
        present: false
    line-length:
        level: "error"
        max: 500
```

The output is
```
features/web-bluetooth.yml
  19:18     warning  too few spaces before comment  (comments)
  21:16     warning  too few spaces before comment  (comments)

groups/streams.yml
  2:14      error    no new line character at the end of file  (new-line-at-end-of-file)
```

I leave this all up to you.

**Comment by foolip** [comment]
Thanks for showing the output @szepeviktor! The "no new line character at the end of file" was a surprise, and it turns out we weren't running Prettier for all YAML files. I've fixed that in https://github.com/web-platform-dx/web-features/pull/1487.

I do like having a tool to automatically format stuff, even if sometimes makes code ugly, but since we're already using Prettier I think we'd want some problem that Prettier can't fix that another tool can.

I'll go ahead and close this, but thank you for the suggestion and helping us catch that the Prettier config wasn't working.

**Comment by szepeviktor** [comment]
Glad to contribute.
