### ISSUE TITLE
web-features doesn't surface ranged dates

### ISSUE THREAD

**Issue by LeoMcA** [web-platform-dx/web-features#1501]
Once https://github.com/mdn/yari/pull/11536 has been merged, we'll support ranged dates on MDN and display them slightly differently, like so:

![Screenshot 2024-07-24 at 16-33-49 Element mousedown event - Web APIs MDN](https://github.com/user-attachments/assets/275d9a64-5a60-4002-a85c-7df35e099b4c)

It seems like the ranged dates aren't being exposed in the 1.0.0 version of web-features, I had to manually adjust the data locally to test this.

It would also be nice to return a ranged date when we know we're being limited by the earliest version of Edge.

**Comment by ddbeck** [comment]
Thanks for opening this, @LeoMcA.

> I had to manually adjust the data locally to test this.

Just to confirm whether there's data bug here: did you fake something (e.g., adding a range to something that wouldn't have had one anyway)? Or did you find a feature that you though _ought_ to have had a range, but did not?

> It seems like the ranged dates aren't being exposed in the 1.0.0 version of web-features, I had to manually adjust the data locally to test this.

I think that's because no features in 1.0 had a ranged date—they were all certain (though perhaps @foolip could confirm that for me). When we start publishing the per-key statuses, you should get lots of individual BCD keys with ranges, however. That's still waiting on https://github.com/web-platform-dx/web-features/pull/1407.

> It would also be nice to return a ranged date when we know we're being limited by the earliest version of Edge.

Could you chime in on https://github.com/web-platform-dx/web-features/issues/623, which is about this? I don't think we want to overload "≤" to mean **both** "uncertain because we don't have perfectly accurate date for this" **and** "at the boundary of the Baseline definition" but a consumer perspective on this would be helpful.

One last thing: strictly speaking, "since before" in the Baseline banner may not be correct. The meaning of a ≤ date is closer to "no later than" or "at worst." If we do more research to solidify those values, it might not shift to an earlier date at all, only that the uncertainty was removed.

**Comment by LeoMcA** [comment]
> Just to confirm whether there's data bug here: did you fake something (e.g., adding a range to something that wouldn't have had one anyway)? Or did you find a feature that you though ought to have had a range, but did not?

No, you're right: I faked something that didn't have a date, though mid-flow I reckoned it should and made a mental note to file this issue without checking - I just went through and every ranged browser version in the current release isn't the browser "setting" the baseline low date.

> I think that's because no features in 1.0 had a ranged date—they were all certain

Indeed, no bug here.

> Could you chime in on https://github.com/web-platform-dx/web-features/issues/623, which is about this?

Will do!

> One last thing: strictly speaking, "since before" in the Baseline banner may not be correct. The meaning of a ≤ date is closer to "no later than" or "at worst." If we do more research to solidify those values, it might not shift to an earlier date at all, only that the uncertainty was removed.

Yes good point, I'll remove the "before" string for now, and we can introduce it later if needed based on the result of #623.
