### ISSUE TITLE
Incorrect baseline badge of Document Picture-in-Picture API

### ISSUE THREAD

**Issue by skyclouds2001** [web-platform-dx/web-features#1792]
the badge indicate chrome is not supported and edge is supported. this is incorrect, per BCD, chrome is also supported and has the same support data with edge

![image](https://github.com/user-attachments/assets/a6486599-bd90-415e-a16c-9bfcde12ebef)

for example, see [Document Picture-in-Picture API](https://developer.mozilla.org/en-US/docs/Web/API/Document_Picture-in-Picture_API)

**Comment by ddbeck** [comment]
Thanks for raising this, @skyclouds2001. I took a closer look and this status is correct, though I understand the confusion here. This is a strange case, so it's hard to see why this appears on MDN the way it does.

This feature is one of a small set of features that is supported in Chrome but **not** Chrome for Android. The banner on MDN uses a single X or check mark to represent Chrome and Chrome for Android together. Since one of the two browsers doesn't support this, it shows the orange X.

I hope this explains why this feature was marked as it was. Let us know if you have any questions. Thank you!

**Comment by skyclouds2001** [comment]
> This feature is one of a small set of features that is supported in Chrome but **not** Chrome for Android. The banner on MDN uses a single X or check mark to represent Chrome and Chrome for Android together. Since one of the two browsers doesn't support this, it shows the orange X.

Thanks, now I understand why it is

**Comment by captainbrosset** [comment]
The MDN team might interested in seeing this, and perhaps think about how the banner could be improved to convey the right information. Developers interested in desktop only, for example, would get the wrong idea here.

@Rumyra for visibility.
