### ISSUE TITLE
What is a feature?

### ISSUE THREAD

**Issue by foolip** [web-platform-dx/web-features#2]
What is the granularity of features that makes sense to track for availability and adoption? Different data sets like BCD, caniuse.com and chromestatus.com, have different granularities.

https://github.com/w3c/webref/issues/597 is an issue about this, one way that we could solve it, but not the only way.

My own sense is that caniuse.com (the entries not imported from MDN) has the granularity that makes the most sense to web developers, with entries like these:

https://caniuse.com/arrow-functions
https://caniuse.com/details
https://caniuse.com/flexbox
https://caniuse.com/flexbox-gap
https://caniuse.com/web-serial

**Comment by foolip** [comment]
cc @voxpelli

**Comment by voxpelli** [comment]
Another data source is the polyfill.io data which eg. [checks and polyfills `WebAnimation` in its entirety](https://github.com/Financial-Times/polyfill-library/blob/master/polyfills/WebAnimations/detect.js) rather than breaking it down into parts like eg. BCD is doing.

This is one of the things I found while working on #3 and one which makes it harder to say whether a feature is supported in the browser itself or through a polyfill.

**Comment by tidoust** [comment]
Closing the issue as "being addressed": the project is learning as it progresses, adding group features on a regular basis at a relatively coarse granularity, with a mapping to fine-grained BCD features to compute support.

I note polyfills were discussed in #189.
