### ISSUE TITLE
Baseline: Treat Samsung Internet as a "major browser"

### ISSUE THREAD

**Issue by dfabulich** [web-platform-dx/web-features#216]
I was clicking around a little bit on caniuse, looking for outlier features that didn't get to 95% market share as fast as I might expect.

I noticed https://caniuse.com/beforeafterprint which is still at only 94.12% share, despite being supported in Chrome, Edge, Firefox, and Safari since 2019-09-19. So, what's the holdup? Samsung Internet doesn't support it yet.

Then I looked at CSS `clamp()` https://caniuse.com/css-math-functions which is still only at 93.88%, despite being supported in the big four browsers since 2020-04-08. (Safari was the last to support it.) Samsung Internet is, again, responsible for the holdup, because Samsung Internet shipped the feature two months later, in June 2020. (And, ah, Samsung users upgrade kinda slowly.)

Other caniuse features where Samsung Internet was the last browser to support it, and are not yet at 95% market share:

* https://caniuse.com/css-revert-value
* https://caniuse.com/css-image-orientation
* https://caniuse.com/css-matches-pseudo
* https://caniuse.com/css-not-sel-list
* https://caniuse.com/css-cascade-layers

When I ask myself the question, "is it safe to use these features if major browsers support it, but Samsung Internet doesn't?" I think: Samsung Internet is a browser under active development, with a global market share rivaling Firefox.

If Firefox is on the the list, then, I claim, Samsung Internet should be on the list, too.

**Comment by romainmenke** [comment]
see : https://github.com/web-platform-dx/feature-set/issues/179

**Comment by atopal** [comment]
That's the data side of the argument and it's valid, the other side of the argument is about developer perception and behavior. When we ask developers which browsers they are waiting for before they start using a feature, Samsung Internet is usually not on that list. I can only speculate why that is, maybe people are not getting feedback about issues in Samsung Internet and therefore are less likely to consider it a blocker? Either way, any recommendation would need to consider developer expectations as well as the data.

**Comment by foolip** [comment]
@dfabulich have you tested the "beforeprint" event in Samsung Internet? https://developer.mozilla.org/en-US/docs/Web/API/Window/beforeprint_event#browser_compatibility claims it is supported, so either caniuse or BCD is wrong here.

Have you found any other features which aren't available in Samsung Internet, and which seemingly aren't on their way either?

**Comment by tidoust** [comment]
The Samsung Internet browser has not been included in the [Core browser set](https://github.com/web-platform-dx/web-features/blob/main/docs/baseline.md#core-browser-set) for now. One consideration that makes it difficult to integrate Samsung Internet directly today is that the support data in BCD for Samsung Internet is more and more maintained through "mirroring", in other words derived automatically from support in Chrome.

The 30-month duration since the keystone date was partly selected to cater for the time needed by other browsers based on one of the core browsers to integrate the feature. In other words, a feature with Baseline High status should be supported in Samsung Internet too.

The list of browsers that ought to be part of the Core browser set will be reviewed annually. If developers feedback report issues with baseline high features on Samsung Internet, that would be a good signal that the definition needs to be amended.

**Comment by romainmenke** [comment]
I don't want to revive this ticket, but I do think it is important to point out that Edge has exactly the same aspect of having only mirrored data since it switched to blink as its engine. So that should not be seen as a barrier if future survey responses mention Samsung Internet more than they do today.

**Comment by captainbrosset** [comment]
I agree with @romainmenke that the mirroring of some/most of the BCD data doesn't really tell us much. In fact, even if most of the BCD data is mirrored from Chrome to Edge, not **all** of it is. There are, and always will be, small differences.
