### ISSUE TITLE
Update name of :state() to be more specific

### ISSUE THREAD

**Issue by DanielRyanSmith** [web-platform-dx/web-features#2205]
Currently, the name of the [:state()  CSS pseudo-class feature](https://github.com/web-platform-dx/web-features/blob/main/features/state.yml) is simply "state". This name is very generic and it is hard to differentiate what feature is being referenced at a glance. Questions are arising about this [Chromium code reviews](https://chromium-review.googlesource.com/c/chromium/src/+/5972811/comment/439127d1_b68ba000/). Is it possible to update the name of this feature to have a more specific name?

**Comment by atopal** [comment]
@jamesnw what do you think?

**Comment by jamesnw** [comment]
I'm pretty hesitant to do this. Changing the feature ID is a breaking change, and it would be difficult to make it longer while honoring the [identifiers style guide](https://github.com/web-platform-dx/web-features/blob/main/docs/guidelines.md#identifiers). 

The purpose of the identifier is to provide a unique id for a feature, but it is not a requirement that it clearly disambiguate from other features by itself.  We have multiple other identifiers that could be confusing for a variety of reasons, such as `object` or `is`, and I don't think that's a problem. 

In the context of a `WebDxFeature` enum, I also don't find `state` particularly ambiguous. It's a term that could potentially be used in form validity or the History API, but those are generally properties of a feature, and not a full feature.

I do think it is useful to use the feature's name rather than identifier when displaying it to users.
