### ISSUE TITLE
Availability: what is 100%?

### ISSUE THREAD

**Issue by foolip** [web-platform-dx/web-features#223]
https://github.com/Fyrd/caniuse/issues/6733 has brought to light a question that might impact the definition of Baseline.

The sum of Chrome+Edge+Firefox+Safari on [statcounter](https://gs.statcounter.com/browser-market-share#monthly-202305-202305-bar) is 91.66%. When we talk about availability of a feature to end users, should we target 95% (or something) of _all_ users, or users of the targeted browsers?

An implication of saying all users is that there must be an "other" category, since we won't have a fully exhaustive breakdown of known browser brands that add up to 100%.

**Comment by dfabulich** [comment]
IMO: All users. The purpose of Baseline is to tell developers which features are "safe to use."

https://web.dev/baseline/

> Web Platform Baseline gives you clear information about which web platform features are safe to use in your projects today. When reading an article, or choosing a library for your project, if the features used are all part of Baseline, you can trust the level of browser compatibility. By aligning with Baseline, there should be no surprises when testing your site.

If the goal is "no surprises," then I think it would be having up to 8.34% of users not be able to use the feature would count as a "surprise."

**Comment by romainmenke** [comment]
Only targeting Chrome/Edge/Firefox/Safari would be highly problematic and would be hostile towards all other vendors, like Samsung Internet, Opera, ...

I think it's fine to highlight a few browsers in UI on MDN when developers indicate that they mostly care about Chrome/Edge/Firefox/Safari.

But considering a feature safe based only on the adoption of these browsers would create a cycle where developers don't target all browsers, which makes the experience worse for end users of those browsers, which would push users towards Chrome/Edge/Firefox/Safari, which would reinforce the notion that only those 4 are important.

--------


That said I think it would be fine to have a two tiered threshold.

A first threshold could be "discount those browsers developers absolutely do not need to support".

I think IE falls in this category.
It's a browser that is no longer supported by the vendor and has plenty of alternatives.

There will be developers that still have projects targeting IE, but these developers will be aware of this and will use more specialized tooling to help them.

The remaining usage of IE is partly because some users are really stuck on old devices and this is their only gateway to the internet, but another part of users only still use IE to access legacy software while having access to other other browsers.

I don't think it is harmful to just ignore usage of IE at this point.

N% of all users not on long dead browsers seems like an ok system to me.

**Comment by dfabulich** [comment]
If we define Baseline based on market share (or if we use market share as a guideline to define Baseline based on time), I don't think it makes sense to identify browsers to specifically exclude.

The only reason developers don't need to support IE is that its market share is low enough to be ignorable, which is to say, we should target 95% share of all users, and it just turns out that IE will be in the ignorable 5%.

Today, Firefox has 2.77% market share, and [Firefox has been declining in market share for years.](https://gs.statcounter.com/browser-market-share#monthly-200901-202305) IE11 came out in 2013, but it still had more than 2.77% market share until 2019.

Let's suppose Firefox continues to fall in share, but continues shipping new releases. At what point would we discount it as a browser that we absolutely do not need to support? 1% market share? 0.5%? (What if it briefly dips below 1% and then bounces back up above the threshold?) Similarly, at what point did IE become a browser that developers don't need to support? 2019? 2020? 2022?

I think these questions really can't be answered; if we just focus on market share for all users, we don't need to answer them, or make tough judgment calls on when to declare the "death" of a browser.

**Comment by romainmenke** [comment]
I think a definition can be agreed upon that matches IE but doesn't matches Firefox:
- no longer receives security patches
- not installable through normal channels
- has a replacement

**Comment by dfabulich** [comment]
That only became true of IE last year, at IE's declared End of Life on June 15, 2022. But on that day, IE had 0.29% share.

IMO, 2022 would have been much too late to ignore IE, and I think a market-share based analysis incorporating all users and targeting 95% coverage would have shown that automatically, without having to define special criteria.

**Comment by foolip** [comment]
This issue is about what to do when the set of browsers targeted do not cover 100% of users, which is going to be the case even if we include every browser we can name.

It's true that if enough browsers are included it is possible to get to 95% or 98% availability, but 100% will not be possible.

Note that there's no proposal to show a percentage alongside the Baseline logo, so this is a question of Baseline definition, not how it's presented.

**Comment by atopal** [comment]
We already hav a special case of this where features make sense on mobile, but not on desktop. Using marketshare alone in those cases would give a misleading impression. 

I'm thinking that the definition should be understandable by developers, and not too complex. To deal with the unnamed browsers, maybe include them in the share calculation, but ensure that the definition has something like "always over 90%"?

**Comment by tidoust** [comment]
This issue was created as part of discussions to converge on an updated Baseline definition. Now done and deployed on MDN and Can I Use. The group converged on a 30-month window since the keystone date as a proxy to "high total market share support". Closing this issue accordingly.

The group is looking for better market share data and expects to take that data into account when the Baseline definition gets reviewed every year.
