### ISSUE TITLE
Baseline: How do we deal with the inherent inaccuracy of the underlying data for our definition (eg marketshare)?

### ISSUE THREAD

**Issue by atopal** [web-platform-dx/web-features#239]
This was one of the issues we prioritized during our workshop on Baseline on June 16.

**Comment by ddbeck** [comment]
I'm going to interpret this expansively, to include both of these problems:

- Sources of data for market share have known accuracy problems (e.g., Statcounter lumps Chrome for Android together, but separates other browsers by release)
- Sources of data for market share have uncorrectable or unknowable sources of error or bias (e.g., Statcounter's methodology is opaque; RUM Archive sites may not be representative)

I think the solution to both of these problems is to define baseline **only** in terms that a web developer, on their own, might be able to independently verify.For instance, the definition of Baseline

de-emphasize the selection of a metric or data source as part of the definition of Baseline.

satisficing

**Comment by ddbeck** [comment]
I'm going to interpret this question expansively, to include both of these problems:

- Sources of data for market share have known accuracy problems (e.g., Statcounter lumps Chrome for Android together, but separates other browsers by release)
- Sources of data for market share have uncorrectable or unknowable sources of error or bias (e.g., Statcounter's methodology is opaque; RUM Archive sites may not be representative)

My short answer to this question is: decouple market share from the definition setting process (which should consider market share) from the definition itself (which shouldn't).

My longer answer:

I think the solution to both of these problems is to define baseline **only** in terms that a web developer, on their own, might be able to independently verify (i.e., by testing a feature in several web browsers). For instance, the definition of Baseline might name a specific set of browser releases or some timeline (e.g., days elapsed since release) required to qualify a feature as Baseline.

The owners of the Baseline definition should select qualification criteria that **approximates** a market share, or even have it as a specific goal as an outcome the definition (e.g., comparing market share measures to Baseline results might be a good fitness test for the definition). But de-emphasizing the selection of a data source as part of the definition itself has a number of benefits:

- It eliminates a dependence on any one data source. Surprise downtime (or termination) of a data source won't interrupt Baseline status calculations.
- It avoids the complexity of relying on multiple data sources.
- It adds stability and predictability to the definition and its results. Day-to-day or seasonal variations in market share data won't cause features to move back-and-forth across the Baseline threshold. Maintainers and consumers of feature-set will be able to anticipate both how and when features move between Baseline statuses. I'll have more to say about this on https://github.com/web-platform-dx/feature-set/issues/238.

I do think this will require us to do some degree of satisficing with respect to market share (e.g., setting a lowest tolerable bound for market share that's likely to be satisfied by the definition and any reasonable data set, so that we're not constantly revising the definition), but that's something I mean to mention on https://github.com/web-platform-dx/feature-set/issues/237.
