### ISSUE TITLE
eslint plugin for baseline

### ISSUE THREAD

**Issue by TKDev7** [web-platform-dx/web-features#263]
I would love to see an eslint plugin for baseline features, similar to the [compat](https://www.npmjs.com/package/eslint-plugin-compat) plugin

**Comment by romainmenke** [comment]
The `compat` plugin is that plugin.

At this time Baseline can be roughly, but not entirely accurately described as 
> a manually curated list of features that is available in the latest 2 major versions of Safari, Chrome/Edge and Firefox.

Because the `compat` plugin supports `browserslist` you can craft a query that matches the current intention of Baseline :

`last 2 Chrome versions, last 2 ChromeAndroid versions, last 2 Edge versions, last 2 Firefox versions, last 2 FirefoxAndroid versions, Safari >= 15, iOS >= 15`
