### ISSUE TITLE
Timeline based definition for baseline : when browsers drop hardware/os support

### ISSUE THREAD

**Issue by romainmenke** [web-platform-dx/web-features#349]
A timeline based definition should take into account that not all versions/releases are equal.

Sometimes a vendor will drop support for specific OS versions or hardware.
The last version of that given browser that worked on that specific OS or hardware will remain in use for longer than the release just prior or those after it.

**Comment by dfabulich** [comment]
I agree with this, and that's why I'm advocating for a "long timeline" definition for Baseline, like this: "A feature becomes Baseline three years after the last major browser ships support for it," i.e. "three years after the keystone release date."

This keeps the definition of Baseline simple, and the long timeline ensures that we'll get 95%+ marketshare even in the worst case, where older devices can't upgrade.

If you haven't seen it yet, you might enjoy perusing the data in this Keystone Chart Sample:
https://dfabulich.github.io/baseline-calculator/keystone-chart-sample.html It currently shows that the worst-case feature for three years ago, https://caniuse.com/css-math-functions has 95% "tracked" marketshare.

The input data for that is here: https://github.com/dfabulich/baseline-calculator/blob/main/survival-input-data.csv

(Note that caniuse today says css-math-functions only has 92.83% marketshare, but that's because it assumes that untracked "Other" browsers support no features at all. If you click the dropdown in the upper right and switch from "all users" to "all tracked," this feature has 96% marketshare, because "Other" traffic on StatCounter adds up to 3.3% share.)

**Comment by romainmenke** [comment]
A long timeline definition was chosen so I think this issue is resolved.
