### ISSUE TITLE
Possible inconsistency in Baseline rating for `::part()` 

### ISSUE THREAD

**Issue by gingerchew** [web-platform-dx/web-features#530]
On the MDN page for `::part()`, the Baseline component says [that it has limited availability](https://developer.mozilla.org/en-US/docs/Web/CSS/::part).

<img width="628" alt="image" src="https://github.com/web-platform-dx/web-features/assets/26461046/8950499e-0283-496e-983a-9e48461c6cbb">

According to [caniuse](https://caniuse.com/mdn-css_selectors_part), there is 95% global support. [In this article on MDN talking about Baseline](https://developer.mozilla.org/en-US/blog/baseline-evolution-on-mdn/#feature_example), there is a mention of a 30 month waiting period before being considered "Widely available".

> According to the Baseline definition, CSS custom properties became "newly available" on April 5, 2017, with the Edge 15 release, and therefore, became a part of "Baseline 2017". However, availability in all major browsers doesn't mean you can safely use a feature: it takes time for users to update their browsers or, in some cases, they have to update their operating system or even the device itself to get a new browser version. *That's why, only thirty months later, on October 5, 2019,* CSS custom properties were considered "widely available".

Chrome had it in early 2019. Edge didn't inherit it until Early 2020, a couple weeks after Firefox implemented it. Safari was just over a year after Chrome had on 3/23/2020. [Approximate dates from caniuse](https://caniuse.com/mdn-css_selectors_part). It's been 33 months. If it comes down to bugs or tests failing, [Safari is the only one with a 25/25 for wpt tests in the most recent tests](https://wpt.fyi/results/css/selectors/parsing/parse-part.html?label=master&label=experimental&aligned) and there isn't any sort of footnotes on MDN or caniuse.

Since the 30 month waiting period is over, shouldn't `::part()` be classified as Widely Available?

**Comment by tidoust** [comment]
I believe that this is an occurrence of the problem described in #495: the banner that MDN currently displays on an individual feature pages is that of the group this feature is part of. In web-features, `::part()` is part of [`custom-elements`](https://github.com/web-platform-dx/web-features/blob/main/feature-group-definitions/custom-elements.yml), which contains other features that are not yet widely available.

From a web-features perspective, the plan is to expose the baseline status of individual features somehow, so that one can look and tell that the `::part()` feature itself is widely available.

**Comment by gingerchew** [comment]
Okay, that is frustrating, but I understand why it is like that currently. It sounds like the issue has been identified already, so I'll close this :)
