### ISSUE TITLE
Umbrella features for old versions of HTML, CSS and JavaScript

### ISSUE THREAD

**Issue by foolip** [web-platform-dx/web-features#558]
It would be useful to have at least these groups to put a lot of widely supported APIs into:

- HTML 4 (or older)
- HTML 5 (probably up to https://www.w3.org/TR/2017/REC-html52-20171214/)
- CSS 2
- ECMAScript versions as discussed in https://github.com/web-platform-dx/web-features/pull/330#issuecomment-1918688947

I suspect we'll run into harder cases the newer versions we try to add, and in particular I don't think we should try to categorize new JavaScript features primarily by ECMAScript version, but instead by the specific features. Over time they might melt into a grouping feature, however.

**Comment by captainbrosset** [comment]
As a way to move fast on things that have been baseline for a long time, I agree that this is a good idea.
But it kind of makes me sad a little bit, because it doesn't achieve one of the goals we have on the README:

> web-features is an effort to build a shared catalog of features of the web platform [...] feature definitions, which identify and describe capabilities of the web

If we create 3 huge groups for everything that's been supported every year for at least a few years, then we don't really catalog the web platform.
We achieve our goal of making it easy for devs to know what they can use, but we don't achieve our goal of representing a list of features that are organized, roughly sized the same, and that can be browsed to learn what's possible to even do on the web.

**Comment by Elchi3** [comment]
I agree with @captainbrosset but I also think that having larger groups for "snapshots" is useful.  I think "snapshots groups" and "capability groups" in combination are quite interesting actually. I guess my thought is: Why not have both? 

For example, if you have the snapshot groups: ecmascript-3, ecmascript-2018, ecmascript-2024 and the web platform capability group "regular-expressions", you can have:
- ecmascript-3-regular-expressions
- ecmascript-2018-regular-expressions
- ecmascript-2024-regular-expressions

In BCD we could note it like so:

Regex constructor:
```
"tags": [
  "web-features:ecmascript-3",
  "web-features:regular-expressions"
],
```

Regex dotAll:
```
"tags": [
  "web-features:ecmascript-2018",
  "web-features:regular-expressions"
],
```

Also, as you say, snapshot groups are easier to determine than capability groups, because what even is a capability? What does it include?

**Comment by foolip** [comment]
I made up the term "umbrella feature" here, but I don't think they're like regular features. We shouldn't put hundreds of BCD keys into one mega-feature and have that alongside things like Subgrid or BigInt in a hypothetical dashboard/search/thing.

"Why not have both?" is the right answer I think, and I think @Elchi3's "snapshot groups" (which aren't features) are in the right direction for a solution.
