### ISSUE TITLE
CustomElementRegistry.define() "This feature is not Baseline because it does not work in some of the most widely-used browsers."

### ISSUE THREAD

**Issue by conartist6** [web-platform-dx/web-features#561]
MDN URL
https://developer.mozilla.org/en-US/docs/Web/API/CustomElementRegistry/define

What specific section or headline is this issue about?
Baseline

What information was incorrect, unhelpful, or incomplete?
It is incomplete to the point of incorrect to say that browsers do not support this API. Some features of the API, features which are completely undocumented on this page, are not universally implemented. People need to know that what is actually described on this page is baseline usable!

What did you expect to see?
Baseline: Widely Available

Do you have any supporting links, references, or citations?
No response

Do you have anything more you want to share?
No response

MDN metadata

**Comment by tidoust** [comment]
Thanks for the report! This issue (also #562, #530) are occurrences of the problem described in #495: the banner that MDN currently displays on an individual feature page is that of the group this feature is part of, even though the banner is not explicit about that, which is confusing for readers.

In this case, `CustomElementRegistry.define()` is part of [custom-elements](https://github.com/web-platform-dx/web-features/blob/main/feature-group-definitions/custom-elements.yml), which contains other features that are not yet widely available. In other words, the data itself is correct. It does **not** claim that the method itself has limited availability.

We're working on a fix with MDN. I propose to leave this issue open in the meantime so that people may notice it on their way to reporting the problem.

**Comment by conartist6** [comment]
I didn't even know what repo to report it in, so I naively reported it where "report an issue" takes you...

**Comment by LeoMcA** [comment]
Thanks for reporting this, I've added this page (and all others from the custom elements group) to a blocklist on MDN so for now the Baseline banner won't show until we've settled on a more general fix to this problem.
