### ISSUE TITLE
CSS :defined - Appears to be discrepancy between Baseline status and support matrix

### ISSUE THREAD

**Issue by jacecotton** [web-platform-dx/web-features#562]
See here https://developer.mozilla.org/en-US/docs/Web/CSS/:defined

Baseline banner says support is limited with no Firefox or Safari support, but the caniuse data (see table at the bottom of the page) says it's had full support since versions 63 and 10, respectively.

From my reading there doesn't seem to be implementation/spec discrepancies with Firefox or Safari, so not sure why this would show unavailable for them.

**Comment by jacecotton** [comment]
Coincidentally I see #561 was just opened by someone else for the JavaScript counterpart to the API. Perhaps it is the differences in implementation for `customElementRegistry.define`, which in turn affect whether `:defined` will match, that accounts for the discrepancy here.

**Comment by tidoust** [comment]
Thanks for the report! This issue and #561 (also #530), are occurrences of the problem described in #495: the banner that MDN currently displays on an individual feature page is that of the group this feature is part of, even though the banner is not explicit about that, which is confusing for readers. We're working on a fix with MDN.

In this case, `:defined` is part of [custom-elements](https://github.com/web-platform-dx/web-features/blob/main/feature-group-definitions/custom-elements.yml), which contains other features that are not yet widely available. In other words, the data itself is correct. It does **not** claim that `:defined` has limited availability.

I had closed #530 as covered by #495, but it's perhaps more useful to keep these issues open so that people bump into them when they consider reporting similar problems.

**Comment by jacecotton** [comment]
That makes sense! It would definitely be helpful seeing additional text basically saying "X is part of a broader feature set Y which does not have full support in some of the most widely-used browsers" or something along those lines. Thanks for the response.

**Comment by LeoMcA** [comment]
Thanks for reporting this, I've added this page (and all others from the custom elements group) to a blocklist on MDN so for now the Baseline banner won't show until we've settled on a more general fix to this problem.
