### ISSUE TITLE
Usage stats: developers vs. users

### ISSUE THREAD

**Issue by foolip** [web-platform-dx/web-features#66]
This came up in https://github.com/web-platform-dx/feature-set/pull/60 but is unresolved.

I made the distinction between "potential" and "actual" usage, while @atopal and @ddbeck reframed it as usage by developers vs. usage by users, which I think is a good framing.

Where we can measure both, we should pick usage by developers as the most meaningful. We should document this, and enforce it in review.

This still leaves some unanswered questions. The Fullscreen API is a good example, where `element.requestFullscreen()` will be called if a user clicks a button or similar, but there's no way to know if a page has a way to go fullscreen. In other words, we can't really measure developer adoption of the Fullscreen API in the same way that we can with the `<picture>` element.

**Comment by ddbeck** [comment]
I have a couple of questions, probably because I don't know if I completely understood the Fullscreen API example.

In that scenario, what does the usage counter actually tell us? Is it that the `element.requestFullscreen()` element was actually called? That is, it records both the developer intention (a developer put `element.requestFullscreen()` in their code somewhere) and a user behavior (a user clicked something that eventually led down that code path)?

More broadly, is it common/typical to for usage counters to be able to detect whether something is _potentially_ callable (e.g., that `element.requestFullscreen()` is _somewhere_ in the sources loaded for a given page)? If such things exist (or could be reasonably requested) then maybe we can get a better sense of developer intent? Or if not, does this mean we'll just have to accept that some usage metrics will be out of bounds? (In #60 you mentioned JS being unlikely to get any kind of metrics, so I suspect the answer is yes but…)

Finally, what's our actual responsibility here? How big a problem is a feature without usage stats URLs? Is this a nice to have thing, or ought such gaps prompt us to go opening bugs and hassling people in a position to bring them into being?

**Comment by ddbeck** [comment]
For Chrome at least, relating web-features to usage stats has moved to Chromium itself and usage stats have been dropped from web-features directly. See https://github.com/web-platform-dx/web-features/pull/1235.

I'm going to close this issue for now, since we've pretty much answered the usage stats question: we don't track them in this project, but want other projects (i.e., the browsers themselves) to use references _to_ web-features entries.
